# Code generated by github.com/posener/goaction. DO NOT EDIT.


FROM golang:1.14.1-alpine3.11
RUN apk add git 

COPY . /home/src
WORKDIR /home/src
RUN go build -o /bin/action ./cmd/goaction

ENTRYPOINT [ "/bin/action" ]
